=== sergiosaura02/RSS/Sergio_Saura_LM_ACT_UT05_01/Act8/sauralibros.dtd
<!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo, autor, genero, anioPublicacion, editorial)>
<!ATTLIST libro
    ISBN CDATA #REQUIRED
    tipo CDATA #REQUIRED
>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (nombre, fechaNacimiento)>
<!ATTLIST autor
    nacidoEnEspaÃ±a (SI | NO) #REQUIRED
>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fechaNacimiento (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT anioPublicacion (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>

=== sergiosaura02/RSS/Sergio_Saura_LM_ACT_UT05_01/Act8/saura_libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libros SYSTEM "sauralibros.dtd">
<libros>
  <libro ISBN="X978-84-473-1315-2" tipo="Ficción">
    <titulo>Don Quijote de la Mancha</titulo>
    <autor nacidoEnEspaña="SI">
      <nombre>Miguel de Cervantes</nombre>
      <fechaNacimiento>29/09/1547</fechaNacimiento>
    </autor>
    <genero>Novela</genero>
    <anioPublicacion>1605</anioPublicacion>
    <editorial>Francisco de Robles</editorial>
  </libro>
  <libro ISBN="X978-84-8164-493-4" tipo="Misterio">
    <titulo>La sombra del viento</titulo>
    <autor nacidoEnEspaña="SI">
      <nombre>Carlos Ruiz Zafón</nombre>
      <fechaNacimiento>25/09/1964</fechaNacimiento>
    </autor>
    <genero>Novela</genero>
    <anioPublicacion>2001</anioPublicacion>
    <editorial>Planeta</editorial>
  </libro>
  <libro ISBN="X978-84-670-1930-3" tipo="Realismo mágico">
    <titulo>Cien años de soledad</titulo>
    <autor nacidoEnEspaña="NO">
      <nombre>Gabriel García Márquez</nombre>
      <fechaNacimiento>06/03/1927</fechaNacimiento>
    </autor>
    <genero>Realismo mágico</genero>
    <anioPublicacion>1967</anioPublicacion>
    <editorial>Sudamericana</editorial>
  </libro>
  <libro ISBN="X978-84-233-3781-6" tipo="Novela">
    <titulo>La colmena</titulo>
    <autor nacidoEnEspaña="SI">
      <nombre>Camilo José Cela</nombre>
      <fechaNacimiento>11/05/1916</fechaNacimiento>
    </autor>
    <genero>Novela</genero>
    <anioPublicacion>1951</anioPublicacion>
    <editorial>Editorial Noguer</editorial>
  </libro>
  <libro ISBN="X978-84-204-0546-8" tipo="Novela">
    <titulo>La Regenta</titulo>
    <autor nacidoEnEspaña="SI">
      <nombre>Leopoldo Alas Clarín</nombre>
      <fechaNacimiento>25/04/1852</fechaNacimiento>
    </autor>
    <genero>Novela</genero>
    <anioPublicacion>1884</anioPublicacion>
    <editorial>Real Academia Española</editorial>
  </libro>
</libros>
