=== sergiosaura02/RSS/Sergio_Saura_LM_ACT_UT05_01/Act4/saura_valores.dtd
<!ELEMENT valores (accion*)>
<!ELEMENT accion (mercado, nombre, mercado-abierto, recomendación, fecha)>
<!ELEMENT mercado (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT mercado-abierto (#PCDATA)>
<!ELEMENT recomendación (#PCDATA)>
<!ELEMENT fecha (día, mes, año)>
<!ELEMENT día (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>

=== sergiosaura02/RSS/Sergio_Saura_LM_ACT_UT05_01/Act4/saura_valores.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE valores SYSTEM "saura_valores.dtd">
<valores>
	<accion>
		<mercado>Madrid</mercado>
		<nombre>Aceralia</nombre>
		<mercado-abierto>SÍ</mercado-abierto>
		<recomendación>3</recomendación>
		<fecha>
			<día>12</día>
			<mes>07</mes>
			<año>2002</año>
		</fecha>
	</accion>
	<accion>
		<mercado>Madrid</mercado>
		<nombre>Repsol</nombre>
		<mercado-abierto>SÍ</mercado-abierto>
		<recomendación>3</recomendación>
		<fecha>
			<día>12</día>
			<mes>07</mes>
			<año>2002</año>
		</fecha>
	</accion>
</valores>
