=== sergiosaura02/RSS/LM_SERGIO_UT05_ACT02/Actividad2/sauracartelera.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://www.ejemplo.com/cartelera"
    xmlns="https://www.ejemplo.com/cartelera"
    elementFormDefault="qualified">

    <xs:element name="cartelera">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="película"
                    maxOccurs="unbounded"
                    type="Película"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Película">
        <xs:sequence>
            <xs:element name="título"
                type="xs:string"/>
            <xs:element name="título_original"
                type="xs:string"
                minOccurs="0"/>
            <xs:element name="nacionalidad"
                type="xs:string"/>
            <xs:element name="género"
                type="xs:string"/>

            <xs:element name="clasificación"
                minOccurs="0">
                <xs:complexType>
                    <xs:sequence/>
                    <xs:attribute name="edad">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="tp"/>
                                <xs:enumeration value="8"/>
                                <xs:enumeration value="7"/>
                                <xs:enumeration value="12"/>
                                <xs:enumeration value="18"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>

            <xs:element name="sin_clasificar"
                minOccurs="0"/>

            <xs:element name="sinopsis"
                type="xs:string"/>
            <xs:element name="director"
                type="xs:string"/>

            <xs:element name="reparto">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="actor"
                            type="xs:string"
                            minOccurs="1"
                            maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="web"
                type="xs:string"
                minOccurs="0"/>

            <xs:element name="cartel"
                type="xs:string"
                minOccurs="0"/>
        </xs:sequence>

        <xs:attribute name="código"
            type="xs:string"/>
        <xs:attribute name="duración"
            type="xs:int"/>

        <xs:attribute name="año"
            type="xs:int"
            default="2003"/>
    </xs:complexType>
</xs:schema>

=== sergiosaura02/RSS/LM_SERGIO_UT05_ACT02 - copia/Actividad2/cartelera.xml
<?xml version="1.0" encoding="UTF-8"?>
<cartelera xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xmlns="https://www.ejemplo.com/cartelera"
                    xsi:schemaLocation="https://www.ejemplo.com/cartelera sauracartelera.xsd">
    <película código="p1"
        duración="152"
        año="2002">
        <título>AQUELLAS JUERGAS UNIVERSITARIAS</título>
        <título_original>Old School</título_original>
        <nacionalidad>Estados Unidos</nacionalidad>
        <género>Comedia</género>
        <clasificación edad="tp" />
        <sinopsis> Mitch, Frank y Beanie son tres amigos treintañeros cuyas vidas no son exactamente lo que esperaban. Mitch tiene una novia ninfómana que se mete en la cama con el primero que agarra. Frank se ha casado y su matrimonio nada tiene que ver con las juergas salvajes que organizaban años atrás. </sinopsis>
        <director>Todd Philips</director>
        <reparto>
            <actor>Luke Wilson</actor>
            <actor>Will Farrel</actor>
            <actor>Vince Vaughn</actor>
        </reparto>
        <web>http://www.uip.es</web>
        <cartel>caratulas/Aquellas juergas.jpg</cartel>
    </película>
    <película código="p17"
        duración="106">
        <título>EL ORO DE MOSCÚ</título>
        <nacionalidad>España</nacionalidad>
        <género>Comedia</género>
        <sin_clasificar />
        <sinopsis> Por una extraña coincidencia del destino, alguien recibe una información extraconfidencial de un anciano en sus últimos segundos de vida: el secreto mejor guardado de la Historia. El receptor, un trabajador de hospital, se lo comunica secretamente a un supuesto amigo. Ambos inician una aventura rocambolesca y llena de misterio. </sinopsis>
        <director>Jesús Bonilla</director>
        <reparto>
            <actor>Jesús Bonilla</actor>
            <actor>Santiago Segura</actor>
            <actor>Alfredo Landa</actor>
            <actor>Concha Velasco</actor>
            <actor>Antonio Resines</actor>
            <actor>Gabino Diego, María Barranco</actor>
            <actor>María Barranco</actor>
        </reparto>
    </película>
</cartelera>
