=== sergiosaura02/RSS/Sergio_Saura_LM_ACT_UT05_01/Act6/saura_videoclub.dtd
<!ELEMENT videoclub (factura+)>
<!ELEMENT factura (datoscliente, datosticketfactura)>
<!ELEMENT datoscliente (nombre, apellido, DNI, telefono)>
<!ATTLIST datoscliente identificador CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>

<!ELEMENT datosticketfactura (resguardo_factura, alquileres?, compras?)>

<!ELEMENT resguardo_factura (importe_total)>
<!ELEMENT importe_total (#PCDATA)>
<!ATTLIST importe_total formapago (efectivo | tarjeta) #REQUIRED>
<!ELEMENT alquileres (pelicula*)>
<!ATTLIST alquileres fecha_devolucion CDATA #REQUIRED>

<!ELEMENT pelicula (titulo, genero, duracion, actor+, caratula?)>
<!ATTLIST pelicula idPelicula ID #REQUIRED>
<!ATTLIST pelicula valoracion CDATA #REQUIRED>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>

<!ELEMENT actor (nombre_actor, apellidos_actor)>
<!ELEMENT caratula (#PCDATA)>

<!ELEMENT nombre_actor (#PCDATA)>
<!ELEMENT apellidos_actor (#PCDATA)>

<!ELEMENT compras (DVD*, Cinta*)>
<!ELEMENT DVD (titulo, fecha_salida, (extras | no_extras))>
<!ELEMENT fecha_salida (#PCDATA)>
<!ELEMENT extras EMPTY>
<!ELEMENT no_extras EMPTY>

<!ELEMENT Cinta (formato, (rebobinada | no_rebobinada))>
<!ELEMENT formato (#PCDATA)>
<!ELEMENT rebobinada EMPTY>
<!ELEMENT no_rebobinada EMPTY>

=== sergiosaura02/RSS/Sergio_Saura_LM_ACT_UT05_01/Act6/saura_videoclub.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videoclub SYSTEM "saura_videoclub.dtd">
<videoclub>
    <factura>
        <datoscliente identificador="F10">
            <nombre>Juan</nombre>
            <apellido>Fernandez</apellido>
            <DNI>47739549S</DNI>
            <telefono>933486305</telefono>
        </datoscliente>
        <datosticketfactura>
            <resguardo_factura>
                <importe_total formapago="efectivo"></importe_total>
            </resguardo_factura>
            <alquileres fecha_devolucion="27/03/2024">
                <pelicula idPelicula="MJ" valoracion="5/5">
                    <titulo>Mundo Jurásico</titulo>
                    <genero>acción</genero>
                    <duracion>2h 4min</duracion>
                    <actor>
                        <nombre_actor>Bryce</nombre_actor>
                        <apellidos_actor>Dallas Howard</apellidos_actor>
                    </actor>
                    <actor>
                        <nombre_actor>Chris</nombre_actor>
                        <apellidos_actor>Pratt</apellidos_actor>
                    </actor>
                    <actor>
                        <nombre_actor>Nick</nombre_actor>
                        <apellidos_actor>Robinson</apellidos_actor>
                    </actor>
                </pelicula>
                <pelicula idPelicula="OC" valoracion="3/5">
                    <titulo>Operación camaron</titulo>
                    <genero>comedia</genero>
                    <duracion>105min</duracion>
                    <actor>
                        <nombre_actor>Carlos</nombre_actor>
                        <apellidos_actor>Librado</apellidos_actor>
                    </actor>
                    <actor>
                        <nombre_actor>Natalia</nombre_actor>
                        <apellidos_actor>De Molina</apellidos_actor>
                    </actor>
                    <actor>
                        <nombre_actor>Miren</nombre_actor>
                        <apellidos_actor>Ibarguren</apellidos_actor>
                    </actor>
                    <caratula>caratulas/c0360.jpg</caratula>
                </pelicula>
            </alquileres>
            <compras>
                <DVD>
                    <titulo>avatar</titulo>
                    <fecha_salida>15/04/2010</fecha_salida>
                    <no_extras/>
                </DVD>
                <Cinta>
                    <formato>VHS</formato>
                    <no_rebobinada/>
                </Cinta>
            </compras>
        </datosticketfactura>
    </factura>
</videoclub>
